export const TYPES = {
  EMPTY: 0,
  WALL: 1,
  SAND: 2,
  WATER: 3,
  WOOD: 4,
  STONE: 5,
  ICE: 6,
  LAVA: 7,
  SEED: 8,
  PLANT: 9,
  FIRE: 10,
  SMOKE: 11,
  GAS: 12,
  FIREWORK: 13,
  ACID: 14,
  CLONE: 15,
  ANT: 16,
  TREE: 17,
  SUN: 18,
  MOON: 19,
  CLOUD: 20,
  LIGHTNING: 21,
  ELECTRIC_WATER: 22,
  FLOWER_PINK: 23,
  FLOWER_1: 24,
  FLOWER_2: 25,
  FLOWER_3: 26,
  SNOW: 27,
  FIREWORK_ACTIVE: 28,
  SPARK_YELLOW: 29,
  SPARK_PINK: 30,
  SPARK_BLUE: 31,
  SPARK_GREEN: 32,
  STEAM: 33,
  LEAF_AUTUMN: 34,
  WIND: 35,
  FIREWORK_STAGE1: 36,
  FIREWORK_STAGE2: 37
};

export const ELEMENTS = {
  [TYPES.EMPTY]: { id: TYPES.EMPTY, name: '지우개', color: [0, 0, 0], type: 'empty' },
  [TYPES.WALL]: { id: TYPES.WALL, name: '벽', color: [128, 128, 128], type: 'solid', immovable: true },
  [TYPES.SAND]: { id: TYPES.SAND, name: '모래', color: [230, 200, 120], type: 'powder' },
  [TYPES.WATER]: { id: TYPES.WATER, name: '물', color: [60, 120, 240], type: 'liquid' },
  [TYPES.WOOD]: { id: TYPES.WOOD, name: '목재', color: [130, 80, 30], type: 'solid', flammable: 0.05 },
  [TYPES.STONE]: { id: TYPES.STONE, name: '돌', color: [160, 160, 160], type: 'solid' },
  [TYPES.ICE]: { id: TYPES.ICE, name: '얼음', color: [180, 220, 255], type: 'solid', melts: true },
  [TYPES.LAVA]: { id: TYPES.LAVA, name: '용암', color: [255, 80, 20], type: 'liquid', hot: true },
  [TYPES.SEED]: { id: TYPES.SEED, name: '씨앗', color: [150, 200, 50], type: 'falling_solid' },
  [TYPES.PLANT]: { id: TYPES.PLANT, name: '식물', color: [40, 180, 60], type: 'falling_solid', flammable: 0.1 },
  [TYPES.FIRE]: { id: TYPES.FIRE, name: '불', color: [255, 50, 0], type: 'gas', life: 30 },
  [TYPES.SMOKE]: { id: TYPES.SMOKE, name: '연기', color: [100, 100, 100], type: 'gas', life: 60 },
  [TYPES.GAS]: { id: TYPES.GAS, name: '가스', color: [200, 255, 200], type: 'gas', flammable: 0.5 },
  [TYPES.FIREWORK]: { 
    id: TYPES.FIREWORK, 
    name: '폭죽', 
    color: [250, 100, 100], 
    type: 'solid', 
    explosive: true,
    warningTitle: '화려한 불꽃축제!',
    warningText: '폭죽에 불을 붙이면 하늘 높이 솟아올라 펑! 하고 예쁜 모양으로 터진답니다. 불꽃축제를 시작해볼까요?'
  },
  [TYPES.ACID]: { 
    id: TYPES.ACID, 
    name: '산성', 
    color: [120, 255, 60], 
    type: 'liquid', 
    acidic: true,
    warningTitle: '산성 액체 사용하기',
    warningText: '산성은 닿는 물건들을 녹여버리는 무서운 초록색 물이에요. 정말 사용할까요?'
  },
  [TYPES.CLONE]: { 
    id: TYPES.CLONE, 
    name: '복제', 
    color: [255, 0, 255], 
    type: 'solid',
    warningTitle: '복제 블록 사용하기',
    warningText: '복제 블록은 닿은 물건을 계속해서 똑같이 만들어내는 마법의 블록이에요. 정말 사용할까요?'
  },
  [TYPES.ANT]: { id: TYPES.ANT, name: '개미', color: [20, 20, 20], type: 'bug' },
  [TYPES.TREE]: { id: TYPES.TREE, name: '나무', color: [70, 120, 40], type: 'falling_solid', flammable: 0.1 },
  [TYPES.SUN]: { 
    id: TYPES.SUN, 
    name: '해(햇빛)', 
    color: [255, 220, 50], 
    type: 'event',
    warningTitle: '햇빛 쨍쨍!',
    warningText: '해가 뜨면 엄청 더워져서 물이 마르고 사막으로 변해요! 해를 띄워볼까요?'
  },
  [TYPES.MOON]: { 
    id: TYPES.MOON, 
    name: '달(달빛)', 
    color: [200, 200, 255], 
    type: 'event',
    warningTitle: '추운 달밤!',
    warningText: '달이 뜨면 너무 추워져서 물이 꽁꽁 얼어버려요! 달을 띄워볼까요?'
  },
  [TYPES.CLOUD]: { id: TYPES.CLOUD, name: '구름', color: [230, 230, 235], type: 'gas' },
  [TYPES.LIGHTNING]: { id: TYPES.LIGHTNING, name: '번개', color: [255, 255, 100], type: 'energy', life: 3, hidden: true },
  [TYPES.ELECTRIC_WATER]: { id: TYPES.ELECTRIC_WATER, name: '전기물', color: [255, 255, 50], type: 'liquid', life: 15, hidden: true },
  [TYPES.FLOWER_PINK]: { id: TYPES.FLOWER_PINK, name: '벚꽃', color: [255, 180, 200], type: 'falling_solid', flammable: 0.1, hidden: true },
  [TYPES.FLOWER_1]: { id: TYPES.FLOWER_1, name: '빨간꽃', color: [255, 100, 100], type: 'falling_solid', flammable: 0.1, hidden: true },
  [TYPES.FLOWER_2]: { id: TYPES.FLOWER_2, name: '노란꽃', color: [255, 220, 50], type: 'falling_solid', flammable: 0.1, hidden: true },
  [TYPES.FLOWER_3]: { id: TYPES.FLOWER_3, name: '보라꽃', color: [150, 100, 255], type: 'falling_solid', flammable: 0.1, hidden: true },
  [TYPES.SNOW]: { id: TYPES.SNOW, name: '눈', color: [240, 240, 255], type: 'falling_solid', flammable: 0, hidden: true },
  [TYPES.FIREWORK_ACTIVE]: { id: TYPES.FIREWORK_ACTIVE, name: '점화된폭죽', color: [255, 150, 50], type: 'solid', hidden: true },
  [TYPES.SPARK_YELLOW]: { id: TYPES.SPARK_YELLOW, name: '노란불꽃', color: [255, 255, 50], type: 'spark', hidden: true },
  [TYPES.SPARK_PINK]: { id: TYPES.SPARK_PINK, name: '핑크불꽃', color: [255, 100, 200], type: 'spark', hidden: true },
  [TYPES.SPARK_BLUE]: { id: TYPES.SPARK_BLUE, name: '파란불꽃', color: [50, 150, 255], type: 'spark', hidden: true },
  [TYPES.SPARK_GREEN]: { id: TYPES.SPARK_GREEN, name: '초록불꽃', color: [50, 255, 100], type: 'spark', hidden: true },
  [TYPES.STEAM]: { id: TYPES.STEAM, name: '수증기', color: [220, 220, 230], type: 'gas', hidden: true },
  [TYPES.LEAF_AUTUMN]: { id: TYPES.LEAF_AUTUMN, name: '낙엽', color: [255, 140, 40], type: 'falling_solid', flammable: 0.3, hidden: true },
  [TYPES.WIND]: { 
    id: TYPES.WIND, 
    name: '가을바람', 
    color: [200, 230, 200], 
    type: 'event',
    warningTitle: '가을바람이 불어와요!',
    warningText: '가을바람이 불면 초록색 나뭇잎들이 예쁜 색으로 물들고 바닥으로 떨어져요! 바람을 불어볼까요?'
  },
  [TYPES.FIREWORK_STAGE1]: { id: TYPES.FIREWORK_STAGE1, name: '폭죽대기1', color: [250, 100, 100], type: 'solid', hidden: true },
  [TYPES.FIREWORK_STAGE2]: { id: TYPES.FIREWORK_STAGE2, name: '폭죽대기2', color: [250, 100, 100], type: 'solid', hidden: true }
};
